apiVersion: v1
kind: Service
metadata:
  name: skylight-engineer-mailreader-llm
  namespace: skylight-engineer-mailreader
spec:
  selector:
    app: skylight-engineer-mailreader-llm
  ports:
    - port: 8080
      targetPort: 8080
