apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: skylight-engineer-mailreader
type: Opaque
stringData:
  POSTGRES_DB: mailreader
  POSTGRES_USER: mailreader
  POSTGRES_PASSWORD: mailreaderpass